services:
  bytebase:
    image: bytebase/bytebase:2.16.0
    container_name: bytebase
    ports:
      - "8080:8080"
    volumes:
      - ./bytebase/data:/var/opt/bytebase
  pg1:
    image: postgres:15
    container_name: pg1
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
  pg2:
    image: postgres:15
    container_name: pg2
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
  pg3:
    image: postgres:15
    container_name: pg3
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
  pg4:
    image: postgres:15
    container_name: pg4
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
  pg5:
    image: postgres:15
    container_name: pg5
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
  mariadb1:
    image: mariadb:10.6
    container_name: mariadb1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
  mariadb2:
    image: mariadb:10.6
    container_name: mariadb2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
  mariadb3:
    image: mariadb:10.6
    container_name: mariadb3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
  mariadb4:
    image: mariadb:10.6
    container_name: mariadb4
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
  mariadb5:
    image: mariadb:10.6
    container_name: mariadb5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
